<?php
return array (
  11 => 
  array (
    'id' => '11',
    'catid' => '22',
    'typeid' => '0',
    'title' => '河北要求防汛抗旱两手硬 夏收夏种夏管一起抓',
    'style' => '',
    'thumb' => '',
    'keywords' => '抗旱 河北',
    'description' => '河北要求防汛抗旱两手硬 夏收夏种夏管一起抓',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=22&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1400597272',
    'updatetime' => '1465046270',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '22',
    'typeid' => '0',
    'title' => '2015年河北4项减排指标全部大幅超额完成标准',
    'style' => '',
    'thumb' => '',
    'keywords' => '河北 减排',
    'description' => '河北新闻网讯（河北日报记者段丽茜）从省政府新闻办6月3日召开的新闻发布会上获悉，经环保部核定，全省2015年化学需氧量、氨氮、二氧化硫和   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=22&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1400597316',
    'updatetime' => '1465046282',
  ),
  13 => 
  array (
    'id' => '13',
    'catid' => '22',
    'typeid' => '0',
    'title' => '“胖墩”学生日益增多 “私房菜”不要经常大鱼大肉',
    'style' => '',
    'thumb' => '',
    'keywords' => '胖墩 私房 学生',
    'description' => '医生名片陈绍萱 男 河北医科大学第一附属医院营养科教授、中国营养学会广西营养专业委员会秘书长 ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=22&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1400597349',
    'updatetime' => '1465046341',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '22',
    'typeid' => '0',
    'title' => '河北将设立高校毕业生创业就业引导基金',
    'style' => '',
    'thumb' => '',
    'keywords' => '高校 河北',
    'description' => '广西山清水秀，靠山临海而居的村民聚集在此，渐渐形成村落、镇，历经多年风雨，形成独特的人文与自然相结合的景观特色。近几年，为了推动广   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=22&id=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1400597385',
    'updatetime' => '1465026058',
  ),
);
?>